"""Initial schema

Revision ID: 967b1661767d
Revises: 
Create Date: 2025-12-04 17:40:16.270146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '967b1661767d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('shadows_created_count', sa.Integer(), nullable=True),
    sa.Column('total_impact_score', sa.Float(), nullable=True),
    sa.Column('current_streak_days', sa.Integer(), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('auto_shadow_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_privacy_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('shadows',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_video_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('key_takeaways', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('average_completion_rate', sa.Float(), nullable=True),
    sa.Column('total_watch_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('shadow_id', sa.String(36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('end_timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('transcript_segment', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shadow_id'], ['shadows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shadow_views',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('shadow_id', sa.String(36), nullable=False),
    sa.Column('viewer_id', sa.String(36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_position_seconds', sa.Float(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('chapters_viewed', sa.JSON(), nullable=True),
    sa.Column('decision_points_viewed', sa.JSON(), nullable=True),
    sa.Column('playback_speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['shadow_id'], ['shadows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_points',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('shadow_id', sa.String(36), nullable=False),
    sa.Column('chapter_id', sa.String(36), nullable=True),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('decision_description', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('alternatives_considered', sa.JSON(), nullable=True),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('user_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shadow_id'], ['shadows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_points')
    op.drop_table('shadow_views')
    op.drop_table('chapters')
    op.drop_table('shadows')
    op.drop_table('users')
    # ### end Alembic commands ###
